---
- name: install, start and enable httpd
  hosts: all
  tasks:
  - name: install package 
    yum:
      name: httpd
      state: latest
  - name: start service
    service:
      name: httpd
      state: started
      enabled: yes
      
- name: test url
  hosts: localhost
  tasks:
  - name: test url
    uri:
      url: https://ansible1
