--- 
- name: create storage 
  hosts: ansible2
  tasks:
  - name: create new partition
    parted:
      name: files
      label: gpt
      device: /dev/nvme0n1
      number: 1
      state: present
      part_start: 1MiB
      part_end: 512MiB
  - name: create another new partition
    parted:
      name: swap
      label: gpt
      device: /dev/nvme0n1
      number: 2
      state: present
      part_start: 512MiB
      part_end: 1GiB
      flags: [ lvm ]
  - name: create a volume group
    lvg:
      vg: vgdata
      pesize: "8"
      pvs: /dev/nvme0n1p1
  - name: create a logical volume
    lvol:
      lv: lvdata
      size: 500M 
      shrink: yes
      force: yes
      vg: vgdata
  - name: create an XFS filesystem
    filesystem:
      dev: /dev/vgdata/lvdata
      fstype: xfs
      force: yes
  - name: mount the filesystem
    mount:
      src: /dev/vgdata/lvdata
      fstype: xfs
      state: mounted
      path: /data
  - name: setup swap
    block:
    - name: make the swap filesystem
      filesystem:
        fstype: swap
        dev: /dev/nvme0n1p2
    - name: activate the swap space
      command: swapon /dev/nvme0n1p2
    when: ansible_swaptotal_mb < 256
