--- 
- name: create storage
  hosts: ansible2
  tasks: 
  - name: create new partition
    parted:
      name: files
      label: gpt
      device: /dev/nvme0n1
      number: 1
      state: present
      part_start: 1MiB
      part_end: 512MiB
  - name: create another partition
    parted:
      name: files
      label: gpt
      device: /dev/nvme0n1
      number: 2
      state: present
      part_start: 512MiB
      part_end: 1GiB
      flags: [ lvm ]
