---
- name: define variable according to diskname detected
  hosts: all
  tasks:
  - ignore_errors: yes
    set_fact:
      disk2name: sda
    when: ansible_facts['devices']['sda']
  - debug:
      msg: 'Disk name is {{ disk2name }}'
