---
- name: create a user with vaulted variables
  hosts: ansible1
  vars_files:
    - secrets.yml
  tasks:
  - name: creating user
    user:
      name: "{{ username }}"
      password: "{{ pwhash }}"
