---
- name: configure web servers
  hosts: web
  tasks:
  - name: this is the {{ web_package }} package
    debug: 
      msg: "Installing {{ web_package }}"
  - name: this is the {{ web_service }} service
    debug:
      msg: "Starting the {{ web_service }}"
